apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: controller-role
rules:
# Custom resources permissions
- apiGroups: ["crds.example.com"]
  resources: ["programas"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["crds.example.com"]
  resources: ["programas/status"]
  verbs: ["get", "update", "patch"]
# Deployment permissions
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Pod permissions (for monitoring and debugging)
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# Events permissions (for logging events)
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: controller-service-account
  namespace: default
roleRef:
  kind: Role
  name: controller-role
  apiGroup: rbac.authorization.k8s.io
