apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccountName: controller-service-account
      containers:
      - name: controller
        image: controller:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KUBECONFIG
          value: ""  # Use in-cluster config
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: controller-service
  namespace: default
spec:
  selector:
    app: controller
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
